controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.4            # adjust with your robot’s geometry
    wheel_radius: 0.05               # adjust with your robot’s geometry
    use_stamped_vel: false
    publish_rate: 50.0
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    enable_odom_tf: true

joint_state_broadcaster:
  ros__parameters: {}